package baseapp.domain;

import java.io.Serializable;
import java.util.Date;

public class Instansi implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_instansi.id
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_instansi.nama
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    private String nama;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_instansi.deskripsi
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    private String deskripsi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_instansi.created_date
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_instansi.updated_date
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_instansi
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_instansi.id
     *
     * @return the value of t_instansi.id
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_instansi.id
     *
     * @param id the value for t_instansi.id
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_instansi.nama
     *
     * @return the value of t_instansi.nama
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    public String getNama() {
        return nama;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_instansi.nama
     *
     * @param nama the value for t_instansi.nama
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    public void setNama(String nama) {
        this.nama = nama == null ? null : nama.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_instansi.deskripsi
     *
     * @return the value of t_instansi.deskripsi
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    public String getDeskripsi() {
        return deskripsi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_instansi.deskripsi
     *
     * @param deskripsi the value for t_instansi.deskripsi
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    public void setDeskripsi(String deskripsi) {
        this.deskripsi = deskripsi == null ? null : deskripsi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_instansi.created_date
     *
     * @return the value of t_instansi.created_date
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_instansi.created_date
     *
     * @param createdDate the value for t_instansi.created_date
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_instansi.updated_date
     *
     * @return the value of t_instansi.updated_date
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_instansi.updated_date
     *
     * @param updatedDate the value for t_instansi.updated_date
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
}