package baseapp.domain;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.id
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.username
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.flag_aktif
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    private Boolean flagAktif;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.role
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.created_date
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.updated_date
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.id
     *
     * @return the value of t_user.id
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.id
     *
     * @param id the value for t_user.id
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.username
     *
     * @return the value of t_user.username
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.username
     *
     * @param username the value for t_user.username
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password
     *
     * @return the value of t_user.password
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password
     *
     * @param password the value for t_user.password
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.flag_aktif
     *
     * @return the value of t_user.flag_aktif
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    public Boolean getFlagAktif() {
        return flagAktif;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.flag_aktif
     *
     * @param flagAktif the value for t_user.flag_aktif
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    public void setFlagAktif(Boolean flagAktif) {
        this.flagAktif = flagAktif;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.role
     *
     * @return the value of t_user.role
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.role
     *
     * @param role the value for t_user.role
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.created_date
     *
     * @return the value of t_user.created_date
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.created_date
     *
     * @param createdDate the value for t_user.created_date
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.updated_date
     *
     * @return the value of t_user.updated_date
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.updated_date
     *
     * @param updatedDate the value for t_user.updated_date
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }
}