package baseapp.dao;

import baseapp.domain.Instansi;
import baseapp.domain.InstansiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface InstansiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_instansi
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    int countByExample(InstansiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_instansi
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    int deleteByExample(InstansiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_instansi
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_instansi
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    int insert(Instansi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_instansi
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    int insertSelective(Instansi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_instansi
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    List<Instansi> selectByExampleWithRowbounds(InstansiExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_instansi
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    List<Instansi> selectByExample(InstansiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_instansi
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    Instansi selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_instansi
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    int updateByExampleSelective(@Param("record") Instansi record, @Param("example") InstansiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_instansi
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    int updateByExample(@Param("record") Instansi record, @Param("example") InstansiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_instansi
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    int updateByPrimaryKeySelective(Instansi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_instansi
     *
     * @mbggenerated Fri Feb 23 19:28:46 WIB 2018
     */
    int updateByPrimaryKey(Instansi record);
}